[package]
name = "lilycrypt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.7.5"
clap = { version = "3.0.5", features = ["derive"] }
hex = "0.4.3"